spring:
  application:
    name: gym-trainingworkload-service
  security:
    user:
      password: user
      name: user
server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
